/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Attempt = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const Question = IDL.Record({
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({ 'questions' : IDL.Vec(Question) });

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'getAllAttempts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Attempt)))],
      ['query'],
    ),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getMyAttempts' : IDL.Func([], [IDL.Opt(IDL.Vec(Attempt))], ['query']),
  'getQuiz' : IDL.Func([], [IDL.Opt(Quiz)], ['query']),
  'getUserAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(Attempt))],
      ['query'],
    ),
  'submitAnswers' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Attempt = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const Question = IDL.Record({
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({ 'questions' : IDL.Vec(Question) });
  
  return IDL.Service({
    'addQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
    'getAllAttempts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Attempt)))],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getMyAttempts' : IDL.Func([], [IDL.Opt(IDL.Vec(Attempt))], ['query']),
    'getQuiz' : IDL.Func([], [IDL.Opt(Quiz)], ['query']),
    'getUserAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(Attempt))],
        ['query'],
      ),
    'submitAnswers' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };